export const COLORS = {
    primary: '#1B3A6B', accent: '#E8501A', green: '#10b981',
    yellow: '#f59e0b', red: '#ef4444', blue: '#3b82f6',
    bg: '#f4f6f8', surface: '#ffffff',
    text: '#0f172a', textDim: '#475569', textFaint: '#94a3b8',
    border: '#e2e8f0',
    coral: '#f97371',
    coralDark: '#ea580c',
};

export const SC = {
    'Loading': '#f59e0b',
    'In Transit': '#3b82f6',
    'Awaiting Start Verification': '#f97316',
    'Awaiting Verification': '#8b5cf6',
    'Completed': '#10b981',
    'Cancelled': '#ef4444', 'Paid': '#10b981', 'Pending': '#f59e0b',
    'OK': '#10b981', 'Due Soon': '#f97316', 'Overdue': '#ef4444',
};

export const TAB_NAV_PERM = { 
    journeys: 'navTrips', 
    payslips: 'navPayments', 
    submit: 'navFuel', 
    costs: 'navCosts', 
    profile: 'navProfile' 
};

export const TAB_TITLE = {
    journeys: 'My Trips',
    submit: 'Fuel Log',
    costs: 'Expenses',
    profile: 'Profile',
    docs: 'Documents',
    maintenance: 'Maintenance',
    payslips: 'Payments',
};

export const S = {
    page: {
        minHeight: '100dvh',
        background: COLORS.bg,
        fontFamily: "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
        paddingBottom: 'calc(92px + env(safe-area-inset-bottom, 0px))',
        paddingTop: 'env(safe-area-inset-top, 0px)',
        maxWidth: 480,
        margin: '0 auto',
        WebkitTapHighlightColor: 'transparent',
    },
    topbar: {
        background: '#ffffff',
        padding: 'max(10px, env(safe-area-inset-top)) 14px 12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        position: 'sticky',
        top: 0,
        zIndex: 100,
        borderBottom: `1px solid ${COLORS.border}`,
        boxShadow: '0 1px 0 rgba(15,23,42,.04)',
    },
    tabBar: {
        position: 'fixed',
        bottom: 0,
        left: '50%',
        transform: 'translateX(-50%)',
        width: '100%',
        maxWidth: 480,
        background: '#fff',
        borderTop: `1px solid ${COLORS.border}`,
        display: 'flex',
        flexWrap: 'nowrap',
        justifyContent: 'space-around',
        zIndex: 100,
        paddingBottom: 'max(10px, env(safe-area-inset-bottom))',
        paddingTop: 6,
        boxSizing: 'border-box',
        boxShadow: '0 -4px 20px rgba(15,23,42,.06)',
    },
    tabBtn: (a) => ({
        flex: '1 1 25%',
        maxWidth: '25%',
        minWidth: 0,
        minHeight: 52,
        padding: '6px 4px 4px',
        border: 'none',
        background: 'none',
        cursor: 'pointer',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 2,
        color: a ? COLORS.accent : COLORS.textFaint,
        fontWeight: a ? 700 : 500,
    }),
    content: { padding: '16px 16px 8px' },
    card: (accent) => ({ background: COLORS.surface, borderRadius: 14, padding: 16, marginBottom: 12, border: `1px solid ${accent ? accent + '33' : COLORS.border}`, borderTop: accent ? `3px solid ${accent}` : undefined, boxShadow: '0 1px 4px rgba(0,0,0,.05)' }),
    sectionTitle: { fontSize: 11, fontWeight: 700, color: COLORS.textFaint, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12, marginTop: 4 },
    badge: s => ({ display: 'inline-block', padding: '3px 10px', borderRadius: 20, fontSize: 11, fontWeight: 700, background: (SC[s] || '#64748b') + '22', color: SC[s] || '#64748b', border: `1px solid ${(SC[s] || '#64748b')}44` }),
    kpi: { fontSize: 10, color: COLORS.textFaint, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4 },
    kpiVal: c => ({ fontSize: 24, fontWeight: 800, color: c || COLORS.text, letterSpacing: -0.5 }),
    btn: v => ({ padding: v === 'sm' ? '8px 14px' : '13px 20px', borderRadius: 10, border: 'none', cursor: 'pointer', fontWeight: 700, fontSize: v === 'sm' ? 12 : 14, background: v === 'ghost' ? '#f1f5f9' : v === 'green' ? 'linear-gradient(135deg,#059669,#10b981)' : v === 'blue' ? 'linear-gradient(135deg,#1B3A6B,#2563eb)' : 'linear-gradient(135deg,#E8501A,#d4400f)', color: v === 'ghost' ? COLORS.textDim : '#fff' }),
    inp: { width: '100%', padding: '14px 14px', borderRadius: 12, border: `1.5px solid ${COLORS.border}`, fontSize: 16, outline: 'none', boxSizing: 'border-box', marginBottom: 12, fontFamily: 'inherit' },
    lbl: { fontSize: 11, color: COLORS.textFaint, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 5, display: 'block' },
    infoRow: { display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: `1px solid ${COLORS.border}`, fontSize: 13 },
    alert: c => ({ background: c + '15', border: `1px solid ${c}44`, borderRadius: 10, padding: '12px 14px', marginBottom: 12 }),
    success: msg => ({ background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 8, padding: '10px 14px', color: '#065f46', fontSize: 13, fontWeight: 600, marginBottom: 12 }),
    errBox: msg => ({ background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 8, padding: '10px 14px', color: '#dc2626', fontSize: 13, marginBottom: 12 }),
};
